name: Clock - In

on:
  workflow_dispatch:

jobs:
  zoho-people:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Clock in
        run: node clock-in.js
