name: ClockIn

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 1-5'

jobs:
  timeclock365:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Clock in
        run: node scripts/timeclock-punch-in.js
        env:
          TIMECLOCK_EMAIL: ${{ secrets.TIMECLOCK_EMAIL }}
          TIMECLOCK_PASSWORD: ${{ secrets.TIMECLOCK_PASSWORD }}

      - name: Save error data
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: timeclock-clock-in
          path: artifacts/

  zoho-people:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Clock in
        run: node scripts/clock-in.js
        env:
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
          ZOHO_TOTP: ${{ secrets.ZOHO_TOTP }}

      - name: Save error data
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: zoho-clock-in
          path: artifacts/
